config/routes.rb
Rails.application.routes.draw do
  # get "/login", to: 'sessions#new' -don't need because we have log in header in app layout
  root "listings#index"
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#destroy'
  get "/exchanges/:listing_id/new", to: 'exchanges#new'
  resources :exchanges, only: [:show, :create]
  resources :listings
  resources :users, only: [:show, :new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "*path", to: "application#path_not_found", via: [:get, :post]
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :renter, class_name: "User"
  belongs_to :listing
  validates_presence_of :listing_id, :renter_id, :start_date, :total_price
  validates :end_date, presence: true
  validate :end_after_start

#---------Validations---------------
  def end_after_start
    if end_date < start_date
      errors.add(:end_date, "End date must be after start date")
    end
  end


#------helper methods----------


  # is there a difference between these two methods?  Can one
  # method be used for both?
  def start_date_format
    self.start_date.strftime("%a, %B %e, %Y")
  end

  def end_date_format
    self.end_date.strftime("%a, %B %e, %Y")
  end


  # same as above--if two functions are so similar, I'd look to combine them
  def get_owner_name
    id = self.listing.owner_id
    owner = User.find(id)
    owner.name
  end


  def get_renter_name
    id = self.renter_id
    renter = User.find(id)
    renter.name
  end


  def get_duration
    ((self.end_date).to_date - (self.start_date).to_date).to_i
  end


  def get_rental_cost
    listing = Listing.find(self.listing_id)
    rental_per_day = listing.rental_price

    rental_cost = rental_per_day * self.get_duration.to_f
  end


end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController

  def show
    #--confirms user is logged in-----
    if current_user != nil  
    # instead of repeating this check, it might be easier to make a 
    # before action where you redirect if not logged in
      @exchange = Exchange.find(params[:id ])
      @renter = User.find(@exchange.renter_id)
      @listing = Listing.find(@exchange.listing_id)
      @owner = User.find(@listing.owner_id)
      #---confirms that user is either renter or owner of the product -------
      if @owner.id != current_user.id && @renter.id != current_user.id
        flash[:notice] = "You can only view Exchanges that you are part of"
        redirect_to user_path(current_user)
      end
    else
      flash[:notice] = "Please log in to see your Exchanges"
      redirect_to root_path
    end
  end

  def new
    #--confirms user is logged in-----
    if current_user != nil
      #--confirms user is coming from a listing show page *required for
       #-listing id
      if params[:listing_id]
        @listing = Listing.find(params[:listing_id])
          #---confirms that user is not the owner of listing -------
          if @listing.owner_id == current_user.id
            flash[:notice] = "You can not rent your own item"
            redirect_to user_path(current_user)
          else
            @exchange = Exchange.new
          end
      else  # I'm not sure how this would happen if user went to a real URL
        flash[:notice] = "Please visit a listing page to create an Exchange"
        redirect_to user_path(current_user)
      end
    else
      flash[:notice] = "Please log in to create an Exchange"
      redirect_to root_path
    end
  end

  def create
    @exchange = Exchange.new(exchange_params)
    @exchange.total_price = @exchange.get_rental_cost
    @listing = Listing.find(@exchange.listing_id)
    #--Confirms that dates do not conflict
    # this logic might be better in the model as a validation function
    if @listing.date_conflict?(@exchange.start_date, @exchange.end_date)
        @exchange.errors.add(:date_conflict, ": Rental times conflict with other exchanges")
        render :new
    elsif @exchange.save
        redirect_to user_path(@exchange.renter_id)
    else
        render :new
    end
  end

  private

  def exchange_params
    params.require(:exchange).permit(:listing_id, :renter_id, :start_date, :end_date, :total_price)
  end

end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/_exchange_summary.html.erb
<p><%= link_to "Product Name: #{exchange.listing.product_name}: Total Price: #{number_to_currency(exchange.total_price)}", exchange_path(exchange)%></p>

app/views/exchanges/new.html.erb
<h1><%=@listing.product_name%></h1>
<h3><%=@listing.address%>, <%=@listing.zip_code%></h3>

<% if @listing.deleted == false %>
  <h4>Dates unavailable:</h4>
    <ul>
      <% @listing.future_exchanges.each do |exchange| %>
        <li><%=exchange.start_date_format%> - <%=exchange.end_date_format%></li>
      <%end%>
    </ul>

  <%= render partial: "/shared/error_partial", locals: {object: @exchange} %>
  <%= form_for @exchange do |f| %>
    <%= f.hidden_field :listing_id, value: @listing.id%>
    <%= f.hidden_field :renter_id, value: current_user.id%>

    <%= f.label :start_date %>
    <%= f.date_field :start_date, min: Time.now %>

    <%= f.label :end_date %>
    <%= f.date_field :end_date, min: Time.now %>

    <%= f.submit  %>
  <% end %>

<%else%>
  <br>
  <br>
  <h3>This item is currently unavailable for rental.</h3>
<%end%>

app/views/exchanges/show.html.erb
<h1>Exchange Show</h1>

<h3>Owner Name: <%= @owner.name %></h3>
<h3>Renter Name: <%= link_to @renter.name, user_path(@renter) %></h3>
<h3>Listing Name: <%= link_to @listing.product_name, listing_path(@listing) %></h3>
<h3>Start Date: <%= @exchange.start_date_format %></h3>
<h3>End Date: <%= @exchange.end_date_format %></h3>
<h3>Duration: <%= @exchange.get_duration %> days</h3>
<h3>Rental Cost: <%= number_to_currency(@exchange.get_rental_cost) %></h3>