config/routes.rb
Rails.application.routes.draw do
  # get "/login", to: 'sessions#new' -don't need because we have log in header in app layout
  root "listings#index"
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#destroy'
  get "/exchanges/:listing_id/new", to: 'exchanges#new'
  resources :exchanges, only: [:show, :create]
  resources :listings
  resources :users, only: [:show, :new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "*path", to: "application#path_not_found", via: [:get, :post]
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :exchanges
  has_many :renters, through: :exchanges
  belongs_to :owner, class_name: "User"

  validates :product_name, presence: true, uniqueness: { scope: :owner_id }
  validates_presence_of :quality, :owner_id, :address, :product_description
  validates_presence_of :item_value, :rental_price, :zip_code, numericality: true
  validates :buy_price, numericality: true, allow_blank: true

#-----------helper methods for date conflicts and displaying only future exchanges-----------
  def future_exchanges
    self.exchanges.select { |exchange| exchange.start_date > Time.now }
  end

  def date_conflict?(st_date, e_date)
    self.exchanges.each do |exchange|
      if !(st_date < exchange.start_date && e_date < exchange.start_date || exchange.end_date < st_date)
        return true
      end
    end
    false
  end

  def self.existing_listings
    self.where(deleted: false)
  end
  

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :find_listing, only:[:show, :edit, :update, :destroy]

  def index
    @existinglistings = Listing.existing_listings
  end

  def show
  end

  def new
    if current_user
      @listing = Listing.new
    else
      flash[:notice] = "You must be logged in to create a listing"
      redirect_to root_path
    end
  end

  def create
    @listing = Listing.new(list_params)
    if @listing.save
      redirect_to listing_path(@listing)
    else
      render :new
    end
  end

  def edit
    if current_user != nil
      #--redirects if owner is not user
      redirect_to listing_path(@listing)  unless @listing.owner_id == current_user.id
    else
      flash[:notice] = "You must be logged in to edit a listing"
      redirect_to root_path
    end
  end

  def update
    if @listing.update(list_params)
      redirect_to listing_path(@listing)
    else
      render :edit
    end
  end

  def destroy
    #--keep acutal database record for analitics
    @listing.deleted = true
    @listing.save
    redirect_to user_path(current_user)
  end

  private

    def list_params
      params.require(:listing).permit(:product_name, :product_description, :item_value, :rental_price, :buy_price, :quality, :address, :zip_code, :owner_id, :deleted)
    end

    def find_listing
      @listing = Listing.find(params[:id])
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_listing_summary.html.erb
<%= link_to listing_path(listing) do %>
<div class="card-body boxBG mb-3 mt-3">
  <div class="card-text">
    <p class="text-center small_hedding">
      <%=listing.product_name%>
    </p>
    <p class="text-center"><%="Rent per day: #{number_to_currency(listing.rental_price)}"%></p>
    <p class="text-center"><%="Buy Price: #{number_to_currency(listing.buy_price)}"%></p>
</div>
</div>

<%end%>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<h3>
  Note: changing the rental price applies only to newly created exchanges and
  making item unavailable to rent does not cancel current exchanges.
</h3>


  <%= render partial: "/shared/error_partial", locals: {object: @listing}%>

  <%= form_for @listing do |f|%>
      <%= f.label :product_name %>
      <%= f.text_field :product_name%><br>

      <%= f.label :product_description %>
      <%= f.text_area :product_description%><br>

      <%= f.label :item_value %>
      <%= f.number_field :item_value%><br>

      <%= f.label :rental_price %>
      <%= f.number_field :rental_price%><br>

      <%= f.label :buy_price %>
      <%= f.number_field :buy_price%><br>

      <%= f.label :quality %>
      <%= f.text_field :quality%><br>

      <%= f.label :address %>
      <%= f.text_field :address%><br>

      <%= f.label :zip_code %>
      <%= f.number_field :zip_code%><br>

      <%= f.hidden_field :owner_id, :value => current_user.id %>

      <%= f.label :deleted, "Available to rent"%>
      <%= f.radio_button :deleted, false%><br>
      <%= f.label :deleted, "Unvailable to rent"%>
      <%= f.radio_button :deleted, true%><br>

      <%= f.submit "Submit Listing"%>
  <%end%>

app/views/listings/index.html.erb
<div class="container mt-4">
  <section class="text-center">
    <h1 class="">All Listings</h1>
  </section>
</div>

<div class="album py-1">
  <div class="container">
    <div class="row">
      <% @existinglistings.each do |listing| %>
        <div class="col-md-4">
          <%=render partial: "listing_summary", locals: { listing: listing } %>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<h1>Create New Listing</h1>


<%= render partial: "/shared/error_partial", locals: {object: @listing}%>


<%= form_for @listing do |f|%>
  <div class="form-row">
    <div class="form-group col-md-5">
        <%= f.label :product_name %>
        <%= f.text_field :product_name, class: "form-control"%>
    </div>
  </div>
    <div class="form-row">
    <div class="form-group col-md-3">
        <%= f.label :quality %>
        <%= f.text_field :quality, class: "form-control"%>
    </div>
    <div class="form-group col-md-1">
        <%= f.label :rental_price %>
        <%= f.number_field :rental_price, class: "form-control"%>
    </div>
    <div class="form-group col-md-1">
        <%= f.label :buy_price %>
        <%= f.number_field :buy_price, class: "form-control"%>
    </div>
    <div class="form-group col-md-2">
        <%= f.label :item_value, "Replacement Price" %>
        <%= f.text_field :item_value, class: "form-control"%>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group">
        <%= f.label :product_description %>
        <%= f.text_area :product_description, class: "form-control", cols: 70%>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-4">
       <%= f.label :address %>
        <%= f.text_field :address, class: "form-control"%>
    </div>
    <div class="form-group col-md-2">
      <%= f.label :zip_code %>
        <%= f.number_field :zip_code, class: "form-control"%>
    </div>
 </div>
 <div class="form-row">
    <div class="form-group">
        <%= f.hidden_field :owner_id, :value => current_user.id %>
        <%= f.submit "Submit Listing"%>
    </div>
 </div>
    
<% end %>


   

    

  

 



   

    

   

  

app/views/listings/show.html.erb
<h1><%= @listing.product_name%></h1>
<h3>Owner: <%=@listing.owner.username%></h3>

<h3>Prices:</h3>
  <p> Rental Price:  <%= number_to_currency(@listing.rental_price)%>  Buy Price:  <%= number_to_currency(@listing.buy_price) %> </p>
<div class="product_description">
  <h3>Item Description:</h3>
    <p>Condition: <%= @listing.quality%></p>
    <%= @listing.product_description%>
</div>

<h3>Location:</h3>
  <p>Address: <%= @listing.address%> <%=@listing.zip_code%></p>
<% if current_user %>  
  <% if current_user.id == @listing.owner_id %>
    <table>
      <p>Exchanges: </p>
          <% if @listing.exchanges.empty? %>
              <p>This listing currently has no active exchanges.</p>
          <% else %>
              <% @listing.exchanges.each do |exchange| %>
              <tr>
              <td>
                  <%=link_to "#{exchange.start_date_format} - #{exchange.end_date_format}",exchange_path(exchange) %>
              </td>
              <td>
                  Rental Value:  <%=number_to_currency(exchange.total_price)%>
              </td>
              </tr>
              <%end%>
          <% end %>
    </table>
  <% end %>
<% else %>
  <% if @listing.exchanges.any? %>
    <h3>Not Available:</h3>
      <ul>
        <% @listing.future_exchanges.each do |exchange|%>
          <li><%=exchange.start_date_format%> - <%=exchange.end_date_format%></li>
        <%end%>
      </ul>
  <%end%>
<% end %>
<% if current_user %>
  <% if current_user.id == @listing.owner_id%>
    <%=link_to "Edit Listing", edit_listing_path(@listing)%>
  <%else%>
    <% if @listing.deleted == false %>
      <%= link_to "Rent this!", "/exchanges/#{@listing.id}/new"%>
    <%else%>
      <p>This is item is no longer available to rent.</p>
    <%end%>
  <% end %>
<% end %>




<!--  if owner then: destory listing button, owner view from if @listings.exchanges shows renter details and flags current renter. button to creat an exchange to buy or rent warn and display toal cost of echange -->