config/routes.rb
Rails.application.routes.draw do
  # get "/login", to: 'sessions#new' -don't need because we have log in header in app layout
  root "listings#index"
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#destroy'
  get "/exchanges/:listing_id/new", to: 'exchanges#new'
  resources :exchanges, only: [:show, :create]
  resources :listings
  resources :users, only: [:show, :new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match "*path", to: "application#path_not_found", via: [:get, :post]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentorbuyourstuff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<!-- google fonts link -->
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic|PT+Sans|Questrial" rel="stylesheet">

    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark boxBG mb-3">
    <a class="navbar-brand" href="/">ROBYStuff</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Listings <span class="sr-only">(current)</span></a>
          </li>
            <% if current_user %>
              <li class="nav-item">
                  <a class="nav-link" href="<%= new_listing_path %>">Create A Listing</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.name %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="<%= user_path(current_user)%>">View Profile</a>
                  <a class="dropdown-item" href="<%= edit_user_path(current_user)%>">Edit Profile</a>
                </div>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="<%= logout_path%>" data-method="delete">Log Out <span class="sr-only">(current)</span></a>
              </li>
            <% else %>
                <li class="nav-item active">
                  <a class="nav-link" href="<%= new_user_path%>" data-method="get">Create New User <span class="sr-only">(current)</span></a>
                </li>
                <%= render "/sessions/new" %>
            <% end %>
        </ul>
      </div>
    </nav>
  <% if flash.notice%>
    <div class="alert alert-danger", role="alert">
      <%= flash.notice %>
    </div>
  <% end %>
  <section class="ml-4 mr-4">
    <%= yield %>
  </section>
  </body>
</html>